Feature/call to action
FNNDSC/ChRIS_store_ui pull request #117
Opened 2021-04-01 06:43 UTC by DivyanshiSingh

This fixes a part of (#102 )

- Duplicated the content from the Quickstart page to the call to action on the landing page.
- Added a button to navigate to /quickstart.
- Added test cases for the call to action component.

2021-04-05 19:14 UTC, jennydaman commented on src/components/Welcome/components/WelcomeDevelopers/WelcomeDevelopers.js
> +          broader ChRIS community of researchers and clinicians.{" "}
Omg thank you for showing me how to do `{" "}`

2021-04-05 19:24 UTC, jennydaman commented
@mairin In my opinion, the wording here is too grandiose. Do you think we should make it more concise or keep it as-is?

> ChRIS is an <strong>open source platform</strong> for medical analytics in the cloud, democratizing the development of image      processing apps within an ecosystem following **common standards, rather than disparate silos**.
>
> A ChRIS Developer account enables you to submit your image processing application as a containerized ChRIS plugin and share it with the broader ChRIS community of researchers and clinicians.

Suggestion:

> _ChRIS_ is an **open-source platform** for medical analytics in the cloud, democratizing the development and usage of image processing software within an ecosystem following **common standards.**
>
> A _ChRIS_ developer account enables you to share your analysis workflows as containerized software with the _ChRIS_ community of researchers and clinicians.

2021-04-07 14:23 UTC, mairin commented
@jennydaman Agreed, and the text changes look perfect to me!

2021-04-07 14:37 UTC, DivyanshiSingh commented
Ok, I will replace the pre-existing content with the content given in the suggestion with the same formatting.

2021-04-07 17:27 UTC, DivyanshiSingh commented
I have made the changes.

2021-04-07 23:12 UTC, jennydaman requested changes
Full-column width at 1920p screen horizontally is too wide. I think you should add empty white-space (or better, a graphical element) to the left or right of the text. You could simply copy/paste the code from "Focus on your data. Not the tools." section.

![Full-page screenshot](https://user-images.githubusercontent.com/20404439/113945652-c2ae5d00-97d4-11eb-8bcb-0df13ca87603.png)

2021-04-08 11:30 UTC, DivyanshiSingh commented
I have added white spaces @jennydaman

2021-04-08 11:43 UTC, jennydaman commented on src/components/Welcome/components/WelcomeDevelopers/WelcomeDevelopers.css
> +  width:70% !important;
`!important` doesn't seem necessary here. Are you using `!important` to match the style of the rest of the CSS code in this repo?

2021-04-08 11:43 UTC, jennydaman commented on src/components/Welcome/components/WelcomeDevelopers/WelcomeDevelopers.js
> +      <Link to="/quickstart" className="btn callToAction-btn btn-primary">
There's already a "Learn More" button nearby but it doesn't work.

We can figure out a good layout in a future PR, what you have here is good.

![screenshot](https://user-images.githubusercontent.com/20404439/114020915-16a15c00-983e-11eb-9707-d6346895722c.png)

2021-04-08 11:45 UTC, DivyanshiSingh commented on src/components/Welcome/components/WelcomeDevelopers/WelcomeDevelopers.css
> +  width:70% !important;
I will remove It as its not required. I think the space is fine right?

2021-04-08 11:47 UTC, jennydaman commented on src/components/Welcome/components/WelcomeDevelopers/WelcomeDevelopers.css
> +  width:70% !important;
Looks fine to me

2021-04-08 11:53 UTC, DivyanshiSingh commented on src/components/Welcome/components/WelcomeDevelopers/WelcomeDevelopers.css
> +  width:70% !important;
I have removed  !important.

2021-04-08 14:55 UTC, mairin commented on src/components/Welcome/components/WelcomeDevelopers/WelcomeDevelopers.js
> +      <Link to="/quickstart" className="btn callToAction-btn btn-primary">
I think the "Learn more" in the "expand the reach..." area should be a "sign up" button not a learn more. the CTA there is to create a ChRIS store account. The Learn more above should point to chrisproject.org

2021-04-08 14:59 UTC, mairin commented
I can't easily build this locally to take a look right now, but based on the screenshots the only comment I have is to make sure the margins of the "expand the reach of your image processing software" are the same as they are for the "focus on your data, not the tools" section. 

This doesn't appear to be an issue in the screenshots but chrisstore.co isn't loading the fonts correctly so when this gets deployed I'd double check and make sure the right font is getting loaded (should be open sans and overpass.) 

@DivyanshiSingh are you planning a separate PR for the icon fixes?

2021-04-08 17:27 UTC, DivyanshiSingh commented
@mairin the margin is the same, but you can recheck. And yes I have created a separate PR #124 for the icon and plugin changes. Do you want me to merge them in one?

2021-04-08 17:41 UTC, mairin commented
> @mairin the margin is the same, but you can recheck. And yes I have created a separate PR #124 for the icon and plugin changes. Do you want me to merge them in one?

Nope, I think its fine to keep them separate, just didn't know your plan there. Looks good to me now!

2021-04-08 17:42 UTC, mairin approved these changes
Looks good!

2021-04-09 05:58 UTC, jennydaman approved these changes

2021-04-09 05:58 UTC, merged