Showing warning when Docker image ends with ":latest"
FNNDSC/ChRIS_store_ui pull request #119
Opened 2021-04-05 18:04 UTC by DivyanshiSingh

This resolves the issue (#113)
1) Created an Alert warning component.

2021-04-05 18:18 UTC, jennydaman commented
Hi @DivyanshiSingh thanks for the PR! I see that this PR also includes the patchset from #114. Typically the better practice would be to have one feature per branch/PR. It's okay for now, I'll review both of them.

2021-04-05 18:19 UTC, DivyanshiSingh commented
ok sure @jennydaman I will be taking care of this for the next issues.

2021-04-05 19:03 UTC, jennydaman requested changes
Optionally, there's a few opportunities for refactoring here like

```javascript
const inputImage = pluginImage.trim();
```

2021-04-05 19:03 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +      const imageName = pluginImage.trim().split(':');
How about this?

```javascript
if (pluginImage.trim().endsWith(':latest')) {
  return this.handleError('do not use :latest');
}
else if {!pluginImage.trim().includes(':')) {
  return this.handleError('tag by version please');
}
```

2021-04-05 19:12 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +      const imageName = pluginImage.trim().split(':');
ok sure @jennydaman I will fix this soon.

2021-04-06 07:32 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +      const imageName = pluginImage.trim().split(':');
I have made the necessary changes please review @jennydaman

2021-04-06 07:33 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +  handleWarning(message) {
I have removed handleWarning() and only using handleError()

2021-04-06 15:19 UTC, jennydaman requested changes

2021-04-06 15:19 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +    const { dockerImageError } = formError || {};
Conditionals (and ternary operators) create a forking in application logic at the cost of increasing code complexity.

A better strategy here would be to have the argument to `this.handleError` be a renderable JSX object. Or, you can make the error box into a stateless React.Component.

e.g.

```jsx
this.handleError(<span>The <code>:latest</code> tag is discouraged.</span>);
```

Then some refactoring to make `this.handleError` work.

2021-04-06 15:19 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +        let tagExample = `docker tag ${inputImage.split(':')[0]} ${inputImage.split(':')[0]}:1.0.1`;
The version string can be fetched by parsing the uploaded plugin representation file.

However this is a lot of work so let's procrastinate on it. If you'd like, add a `// TODO`

Once your feature PR is merged, we can create an issue for it.

2021-04-06 17:17 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +        let tagExample = `docker tag ${inputImage.split(':')[0]} ${inputImage.split(':')[0]}:1.0.1`;
I have done the required changes @jennydaman. Please review.

2021-04-06 17:19 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +    const { dockerImageError } = formError || {};
Used JSX in handleError() to display error message.

2021-04-06 18:28 UTC, jennydaman approved these changes
I have left some comments, though I am happy with how it is right now.

Do you want to work on these things out of interest, or would you like to merge as-is?

It might be more efficient to merge right away, because the entire codebase for ChRIS_store_ui is due for a major rewrite. See https://github.com/FNNDSC/ChRIS_store_ui/issues/101

2021-04-06 18:28 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +        let tagExample = `docker tag ${inputImage.split(':')[0]} ${inputImage.split(':')[0]}:1.0.1`; //TODO
I meant to ask for a more descriptive comment than just `//TODO`, but I can just add this myself after merging

2021-04-06 18:28 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +        return this.handleError(<div>{description} <p><b>Example:</b><br/>{tagExample}<br/>{pushExample}</p></div> );
Pleasantly surprised that this worked as-is, w/o having to change up the code in other places!

2021-04-06 18:28 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.test.js
> +    image: 'dock/image:1.0.1',
It would've been better to add tests for the feature you just added, but we can let it slide for now.

2021-04-06 18:28 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +        return this.handleError(<span>The <code>:latest</code> tag is discouraged.</span>);
![screenshot](https://user-images.githubusercontent.com/20404439/113760260-083f2d00-96e4-11eb-8dd3-ec94f8949377.png)

Styling could be improved

2021-04-08 13:15 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +        return this.handleError(<span>The <code>:latest</code> tag is discouraged.</span>);
Are you referring to the code tag highlighting? Should we remove it? Or do you want to use the Notification component I implemented in #123

2021-04-08 13:30 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +        return this.handleError(<span>The <code>:latest</code> tag is discouraged.</span>);
I was referring to the code tag highlighting. I think we should keep it. Best case would be to add a CSS class, or leave it as-is for now.

2021-04-09 17:01 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +        return this.handleError(<span>The <code>:latest</code> tag is discouraged.</span>);
Ok, leaving it as it is.

2021-04-09 17:32 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.test.js
> +    image: 'dock/image:1.0.1',
I am very new to writing tests, but I have tried to write cases for my changes. Please have a look @jennydaman

2021-04-09 17:34 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +        return this.handleError(<div>{description} <p><b>Example:</b><br/>{tagExample}<br/>{pushExample}</p></div> );
Yeah, we can assign our jsx in a variable and then render it :)

2021-04-09 17:34 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.js
> +        let tagExample = `docker tag ${inputImage.split(':')[0]} ${inputImage.split(':')[0]}:1.0.1`; //TODO
ok sure then.

2021-04-09 18:02 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.test.js
> +    image: 'dock/image:1.0.1',
That's awesome! Looks good to me.

While you're working on https://github.com/FNNDSC/ChRIS_store_ui/issues/101, note that I've been disabling the tests in that branch --- it gets in the way of high turnover.

2021-04-09 18:02 UTC, jennydaman approved these changes

2021-04-09 18:05 UTC, DivyanshiSingh commented on src/components/CreatePlugin/CreatePlugin.test.js
> +    image: 'dock/image:1.0.1',
Yes I noticed it. But still do I have to add the tests there?

2021-04-09 20:47 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.test.js
> +    image: 'dock/image:1.0.1',
You don't have to, not until after the codebase stabilizes.

2021-04-10 05:08 UTC, merged