Post login destination fixed
FNNDSC/ChRIS_store_ui pull request #136
Opened 2021-04-11 16:37 UTC by DivyanshiSingh

Fixes #132 
Used react-router-dom v5 to implement features asked in [FNNDSC/ChRIS_ui#225](https://github.com/FNNDSC/ChRIS_ui/issues/225)

2021-04-11 17:00 UTC, jennydaman requested changes

2021-04-11 17:03 UTC, jennydaman commented
https://github.com/FNNDSC/ChRIS_store_ui/tree/master and https://github.com/FNNDSC/ChRIS_store_ui/tree/pf4 are diverging, we'll fix these later. But right now one change is important to be merged from https://github.com/FNNDSC/ChRIS_store_ui/tree/master into https://github.com/FNNDSC/ChRIS_store_ui/tree/pf4: https://github.com/FNNDSC/ChRIS_store_ui/pull/126

2021-04-11 17:07 UTC, DivyanshiSingh commented on src/components/Router/ProtectedRoute.js
> +          search: `?next=${props.location.pathname}`
Thanks a lot to point out the sharing link issue...I will change it to use only state.

2021-04-12 08:57 UTC, DivyanshiSingh commented on src/components/SignIn/SignIn.js
>        .then((token) => {
done

2021-04-14 08:52 UTC, DivyanshiSingh commented
Are we waiting for few more changes in this PR @jennydaman ?

2021-04-14 19:52 UTC, jennydaman approved these changes

2021-04-14 19:52 UTC, merged