Add Plugin filtering by Category
FNNDSC/ChRIS_store_ui pull request #139
Opened 2021-04-11 22:23 UTC by zrthxn

Added functionality to filter list of plugins by clicking on a category.

**Notes**
- [x] hard-coded the category names
- [x] used backend API to get plugins belonging to each hard-coded category
- [x] The count of categories is accumulated from the plugins that are fetched when the page loads.

![Screenshot (36)](https://user-images.githubusercontent.com/35369637/114320913-e7d4ff80-9b35-11eb-8890-c5e02d33a77b.png)

Partially implements #137

2021-04-11 23:02 UTC, zrthxn commented
@jennydaman Made a new PR with the requested changes.

2021-04-11 23:03 UTC, jennydaman requested changes

2021-04-11 23:03 UTC, jennydaman commented on src/components/Plugins/Plugins.js
>      this.fetchPlugins = this.fetchPlugins.bind(this);
Might be able to use some sugar here.
https://reactjs.org/docs/faq-functions.html

2021-04-11 23:05 UTC, zrthxn commented on src/components/Plugins/Plugins.js
> +        { name: "Visualization", length: 3 },
They'll stay at zero then since no current plugin has those categories. I just thought that'd look bad.

2021-04-11 23:06 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +        { name: "Visualization", length: 3 },
It's the truth ¯\_(ツ)_/¯

2021-04-11 23:09 UTC, zrthxn commented on src/components/Plugins/Plugins.js
>      this.fetchPlugins = this.fetchPlugins.bind(this);
Do you mean something like [this?](
https://reactjs.org/docs/faq-functions.html#class-properties-stage-3-proposal)
```js
fetchPlugins = () => {
  // fetch
}
```

2021-04-11 23:12 UTC, jennydaman commented on src/components/Plugins/Plugins.js
>      this.fetchPlugins = this.fetchPlugins.bind(this);
Yes if supported

2021-04-12 04:33 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +        { name: "Visualization", length: 0 },
Is there a reason why you do not use a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) or regular object instead of an array of entries?

`Map` would be more efficient and greatly simplify the moving parts of `componentDidMount()`

2021-04-12 04:35 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +        { name: "Visualization", length: 0 },
I assume, to keep the rest of code as it is... OK if you are aiming for a minimal patchset.

2021-04-12 11:14 UTC, zrthxn commented on src/components/Plugins/Plugins.js
> +        { name: "Visualization", length: 0 },
It was mainly to maintain compatibility with the PluginCategories component. Changing to a Map makes that one part easier but introduces more complications elsewhere.

2021-04-12 23:54 UTC, jennydaman approved these changes

2021-04-12 23:54 UTC, merged