Button Component: pf4
FNNDSC/ChRIS_store_ui pull request #142
Opened 2021-04-12 13:58 UTC by DivyanshiSingh

Fixes: #101 
1. Created a generalised Button component to be used throughout the project.
2. Replaced all the occurrences of Button (react-patternfly) to use v4 of patternfly

2021-04-12 14:03 UTC, DivyanshiSingh commented
@jennydaman please review this, next I am taking up the notifications component as you asked it to be implemented using pf4.

2021-04-13 00:20 UTC, jennydaman commented on src/components/Button/index.js
> +    icon,
unused `icon`, is this something you intended to implement but found no usages?

2021-04-13 00:21 UTC, jennydaman reviewed
The `history` object is being passed down from a root router element. Maybe it's possible to import `useHistory` into `<Button />` instead?

https://reactrouter.com/web/api/Hooks/usehistory

(not sure, I just found this from a quick search --- lmk what you think)

2021-04-13 07:39 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +    icon,
Yes, I thought of Icon Buttons but found no usages, I will be removing it for now

2021-04-13 08:06 UTC, DivyanshiSingh commented
I have added history in Button component and we can route using the Buttons 'toRoute' prop

2021-04-13 21:25 UTC, jennydaman requested changes

2021-04-13 21:25 UTC, jennydaman commented on src/components/Welcome/components/WelcomeChRIS/WelcomeChRIS.js
> +          onClick={() => {}}
is a no-op required?

2021-04-13 21:25 UTC, jennydaman commented on src/components/Button/index.js
> +const ButtonComponent = (props) => {
I think spread is being misused here.

You should spread the arguments:

```javascript
const ButtonComponent = ({variant, onClick, customClass, loading, toRoute, ...props}) => {
```

Syntax is a bit cleaner and fixes a problem where later on line 22 you have

```javascript
{...props}
```

Without spreading out `children` from `props`, I think you're accidentally putting `childen` into both the attributes and children of `<Button />`

2021-04-14 08:38 UTC, DivyanshiSingh commented on src/components/Welcome/components/WelcomeChRIS/WelcomeChRIS.js
> +          onClick={() => {}}
I don't know whats the function of this button

2021-04-14 08:51 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +const ButtonComponent = (props) => {
I have made the required changes.

2021-04-14 23:39 UTC, jennydaman commented on src/components/Welcome/components/WelcomeChRIS/WelcomeChRIS.js
> +          onClick={() => {}}
The button is a placeholder, though I am asking about

```javascript
          onClick={() => {}}
```

Is it necessary to have this everywhere?

2021-04-15 05:39 UTC, DivyanshiSingh commented on src/components/Welcome/components/WelcomeChRIS/WelcomeChRIS.js
> +          onClick={() => {}}
No we don't need it. I have removed it.

2021-04-15 05:53 UTC, jennydaman commented on src/components/Button/index.js
> +const ButtonComponent = (props) => {
Hmm, I do not see the suggestion implemented.

Besides, what is the point of wrapping Patternfly's `<Button />`? It doesn't seem like the wrapper is doing much. Perhaps to provide the `toRoute` prop but I think importing `useHistory` is easy enough. But that can be up to you. Also the class `chris-button` is undefined.

2021-04-15 05:59 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +const ButtonComponent = (props) => {
ooh sorry for this @jennydaman. I think I missed some commits let me check.

2021-04-15 06:04 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +const ButtonComponent = (props) => {
I wrapped the Button so that we can customize it if needed, but for now I can only see that toRoute is the only customization. Should I remove the wrapper @jennydaman ?

2021-04-15 06:19 UTC, jennydaman commented on src/components/Button/index.js
> +const ButtonComponent = (props) => {
Hmm,on second thought it might be worth keeping. Typically I would try to use the UI components as-is (as how the library developer intends). But customization might be something worth pursuing in the future. Since the ChRIS store's purpose is to be an advertisement, developing our own branding (hence deviating from Patternfly) is a good thing.

2021-04-15 07:17 UTC, jennydaman commented on src/components/Button/button.css
> +    width:70px;
Is a fixed-width something we want to be setting globally to all `<Button />`?
This might make it hard to customize widths of buttons.

2021-04-15 07:17 UTC, jennydaman commented on src/components/Button/index.js
> +        {...otherProps}
Typically, `otherProps` are given to the parent element returned by `render`. Otherwise it's impossible to customize the parent.

2021-04-15 07:17 UTC, jennydaman commented on src/components/Button/button.css
> +.chris-button button{
I think it would be better to give the `other-button` class to `<Button />` instead of using a child selector.

2021-04-15 07:17 UTC, jennydaman commented on src/components/Button/index.js
>          spinnerAriaValueText
Remove undefined attribute

2021-04-15 07:17 UTC, jennydaman commented on src/components/Button/index.js
> +  customClass,
`customClass` seems like an awkward workaround.
Perhaps a better solution would be to give the child `<Button />` a class (if necessary) and then spread `otherProps` as attributes to the parent `<div>` (so if `otherProps` contains `className`, it will be applied to the parent)

2021-04-15 15:16 UTC, DivyanshiSingh commented on src/components/Button/button.css
> +    width:70px;
Removed this and gave other-button class to <Button/>

2021-04-15 15:16 UTC, DivyanshiSingh commented on src/components/Button/button.css
> +.chris-button button{
done

2021-04-15 15:17 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +  customClass,
implemented you suggestions to use otherProps with root element to expose it for customization

2021-04-15 15:17 UTC, DivyanshiSingh commented on src/components/Button/index.js
>          spinnerAriaValueText
done

2021-04-15 15:17 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +        {...otherProps}
changed the approach to make the root element as customizable

2021-04-15 17:02 UTC, jennydaman commented on src/components/Navbar/Navbar.css
> +.login-button .other-button{
Might be able to set colors without using `!important` using the CSS variables as per documentation.
https://www.patternfly.org/v4/components/button/#css-variables

Also I am hesitant about referencing the `other-button` class here. It's fine for now, but I've created a new issue proposing a fix: https://github.com/FNNDSC/ChRIS_store_ui/issues/151

2021-04-15 17:42 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +    <div  {...otherProps}>
I am using a parent wrapper so that in the future if we want an icon button or a loader button both being different from what is provided by patternfly by default, we can add those elements in the parent wrapper along with Button. What do you think about this @jennydaman?

2021-04-15 17:45 UTC, jennydaman commented on src/components/Button/index.js
> +    <div  {...otherProps}>
OK, let's keep in then.

I think loading and icon buttons are both natively supported by PatternFly.

2021-04-15 17:49 UTC, DivyanshiSingh commented on src/components/Button/index.js
> +    <div  {...otherProps}>
Yes but let's say we want a different loader and loader behaviour, I was thinking about that

2021-04-15 17:51 UTC, DivyanshiSingh commented on src/components/Navbar/Navbar.css
> +.login-button .other-button{
I am unable to change the color using css-variables as i think we can't use button variables in Navbar. Also, !important is required to override the color that the Navbar is providing

2021-04-15 18:01 UTC, jennydaman commented on src/components/Navbar/Navbar.css
> +.login-button .other-button{
Hmm, I was a bit fond of the dark button.
![original](https://user-images.githubusercontent.com/20404439/114916431-c8b6c600-9df2-11eb-8f4d-d8acfb206e93.png)
Your blue seems a bit too striking, though it's ok too. Paging @mairin for a professional opinion.
![changed](https://user-images.githubusercontent.com/20404439/114916575-f26fed00-9df2-11eb-87a2-1625e4d5d3f6.png)

BTW you can use CSS variables here.

```css
.login-button .pf-c-button.pf-m-primary {
  --pf-c-button--m-primary--BackgroundColor: red;
}
```

![result](https://user-images.githubusercontent.com/20404439/114916650-0b789e00-9df3-11eb-9f46-6469a6489572.png)

2021-04-15 18:06 UTC, DivyanshiSingh commented on src/components/Navbar/Navbar.css
> +.login-button .other-button{
so should I remove the blue?

2021-04-15 18:11 UTC, mairin commented on src/components/Navbar/Navbar.css
> +.login-button .other-button{
It's the primary call to action so i would keep it filled in blue. If you can shift the blue color to the same blue color that is the bg color of the jumbo below (that is ChRIS blue) it would be better, but the PatternFly default blue is ok.

@jennydaman - the darker button is aesthetically pleasing but doesn't draw the eye as much as it needs to IMHO. when in doubt i think sticking with the PF standard practice is better. I would classify this as a primary button which is why I'd say fill it.

2021-04-16 17:32 UTC, DivyanshiSingh commented
@jennydaman if the color is ok for now, can you merge this PR so that I can use the responsive button in my Autocomplete branch?

2021-04-17 09:45 UTC, jennydaman approved these changes

2021-04-17 09:45 UTC, merged

2021-04-17 11:43 UTC, zrthxn commented
The `useHistory` hook seems to cause this issue on the latest version pulled from the pf4 branch.

![Screenshot (50)](https://user-images.githubusercontent.com/35369637/115111898-453ad780-9fa0-11eb-979f-72550dbcb71e.png)

2021-04-17 11:49 UTC, DivyanshiSingh commented
@zrthxn run ```npm i``` . You must be using older version of reat-router-dom.

2021-04-17 11:50 UTC, zrthxn commented
I have version 5.2.0
Still I'll try