UI Notifications for errors
FNNDSC/ChRIS_store_ui pull request #144
Opened 2021-04-13 07:31 UTC by DivyanshiSingh

Fixes: #13 and #101 
1) Created a reuseable notification component in patternfly-4 to display the error messages.

2021-04-13 20:40 UTC, jennydaman reviewed
Only nitpicks, see review. 

![Preview](https://user-images.githubusercontent.com/20404439/114618067-ee1ec500-9c76-11eb-9b9d-6fe53ac6a9f4.gif)

2021-04-13 20:40 UTC, jennydaman commented on src/errors/HttpApiCallError.js
> +    this.message = error.message;
Could use object spread syntax here (optional).

2021-04-13 20:40 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +      console.log("here")
delete `console.log`

2021-04-14 08:32 UTC, DivyanshiSingh commented on src/components/Dashboard/Dashboard.js
>        return e;
We can either use custom messages as I was using earlier or use the custom response from the backend, but as you said that the backend response is not structured, I think it's best to use the custom messages.

2021-04-14 08:36 UTC, DivyanshiSingh commented on src/components/Plugins/Plugins.js
> +      console.log("here")
console deleted.

2021-04-14 19:43 UTC, jennydaman requested changes

2021-04-14 19:43 UTC, jennydaman commented on src/components/Dashboard/Dashboard.js
>        return e;
We can detect some custom messages simply based on the response (404, wrong content type, timeout, ...)
However that is besides the point. What you added is okay. I was making a comment on the line below, how the code reads

```javascript
catch (e) {
  something();
  return e;
}
```

In general, we shouldn't return anything in the case of an exception, we should either throw it again or give up and do nothing. If we return an exception, we are making a bad situation worse.

However, I took a moment to scroll up and actually read the existing code. It's async spaghetti. The `try` is only wrapping these lines of code:

https://github.com/FNNDSC/ChRIS_store_ui/pull/144/files#diff-e82a9b05e2166cb4373028e8db04cb652be90796eb324ad21dbbf2f5ef9588a9L30-L46

The actual request and errors regarding the request occur during a `Promise`.

I think what was intended here was,

```javascript
client.getPlugin(pluginId)
  .then(plugin => plugin.delete())
  .then(() => this.fetchPlugins())
  .catch(e => this.showNotifications(new HttpApiCallError(e)));
```

Can be cleaner using `async`/`await`. Do you think you could try rewriting this using `async`/`await`?

2021-04-15 05:55 UTC, DivyanshiSingh commented on src/components/Dashboard/Dashboard.js
>        return e;
thanks for pointing this out. I will remove the return statement and rewrite using async/await

2021-04-17 17:14 UTC, DivyanshiSingh commented on src/components/Dashboard/Dashboard.js
>        return e;
changes done please review

2021-04-19 02:18 UTC, jennydaman requested changes
Sorry for the late responses @DivyanshiSingh. This PR is almost ready.

2021-04-19 02:18 UTC, jennydaman commented on src/components/Dashboard/Dashboard.js
> +      response.delete();
Let's  `await response.delete()` as well.

2021-04-19 11:15 UTC, manas2297 commented on src/components/Dashboard/Dashboard.js
> +      response.delete();
done

2021-04-20 19:59 UTC, jennydaman commented on src/components/Dashboard/Dashboard.js
> +      }
else, maybe throw an error to trigger UI notification?

2021-04-20 20:02 UTC, jennydaman commented on src/components/Plugin/Plugin.js
> +        ({ pluginData } = this.state);
Would you remove these parenthesis?

2021-04-20 20:03 UTC, jennydaman commented on src/components/Plugin/Plugin.js
> +      }
else... throw

2021-04-21 07:36 UTC, DivyanshiSingh commented on src/components/Plugin/Plugin.js
> +      }
Can you specify more about what to throw here?

2021-04-21 16:01 UTC, DivyanshiSingh commented on src/components/Plugin/Plugin.js
> +      }
done

2021-04-21 16:01 UTC, DivyanshiSingh commented on src/components/Plugin/Plugin.js
> +        ({ pluginData } = this.state);
done

2021-04-21 16:02 UTC, DivyanshiSingh commented on src/components/Dashboard/Dashboard.js
> +      }
done

2021-04-22 04:39 UTC, jennydaman approved these changes
I myself would be more specific about errors and exception handling (either "unexpected response from server," or in the worst case, "unknown error"), but being more specific about error handling, though it might not be helpful at this level. What you have here greatly improves UX and is good to merge.

2021-04-22 04:39 UTC, merged

2021-04-22 04:52 UTC, DivyanshiSingh commented
Hey, @jennydaman do you have some specific feature in mind that you feel is primarily important to add in pf4. I can take that up in parallel to form. I will raise the PR for the form by today.

2021-04-22 06:57 UTC, jennydaman commented
@DivyanshiSingh it's definitely still about eliminating all trace of `patternfly-react` from the codebase, and maybe upgrading to react v17. They're chores but we must pay off the technical debt before working on the features.