Sort fix
FNNDSC/ChRIS_store_ui pull request #153
Opened 2021-04-17 06:02 UTC by sonylomo

Fixes issue #135 
Added functionality to sort search:

-   alphabetically by author
-   alphabetically by name
-   chronologically by date created

2021-04-23 03:59 UTC, jennydaman requested changes

2021-04-23 03:59 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +      sortFunc: (a, b) => new Date(a.creation_date) + new Date(b.creation_date),
Did you mean to use the `-` operand?

2021-04-23 03:59 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +          (count, current) => (name === current.category ? ++count : count),
A more efficient algorithm can be used here.

Currently you have O(n^2):

```
for every category:
  for every plugin:
    if plugin's category is ..., then increase counter
```

It could be linear, using a `Map` with category name as keys and frequency as values.

```
for every plugin:
  increase count of plugin's category
```

2021-04-23 07:39 UTC, sonylomo commented on src/components/Plugins/Plugins.js
> +      sortFunc: (a, b) => new Date(a.creation_date) + new Date(b.creation_date),
No. I wanted it to be sorted from the latest creation date to the earliest by default. The other way would've been `sortFunc: undefined` - I didn't think that would be a good idea 😅.

2021-04-24 08:08 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +      sortFunc: (a, b) => new Date(a.creation_date) + new Date(b.creation_date),
You have a positive number plus a positive number will always result in a positive number, so this function isn't doing anything.

Maybe you meant

```javascript
// Monday, Tuesday
sortFunc: (a, b) => new Date(a.creation_date) - new Date(b.creation_date)
// Tuesday, Monday
sortFunc: (a, b) => new Date(b.creation_date) - new Date(a.creation_date)
```

2021-04-29 13:26 UTC, sonylomo commented
The tests on `LoadingContainers` are failing, I'm not sure why. They were previously passing.

2021-05-26 01:57 UTC, jennydaman commented
Closing because `pf4` was merged into `master`

2021-05-26 01:57 UTC, closed without merging