Show/Hide password functionality added
FNNDSC/ChRIS_store_ui pull request #156
Opened 2021-04-17 17:07 UTC by somya51p

This PR is associated to issue number #152.
Enabled the show/hide password functionality on the login page as well as the signup page.
@jennydaman @mairin Please review the PR and suggest the changes if any.

![Screenshot from 2021-04-17 21-42-54](https://user-images.githubusercontent.com/64978837/115120844-30286d80-9fcd-11eb-9733-1c228f3d5b1c.png)

![Screenshot from 2021-04-17 21-43-06](https://user-images.githubusercontent.com/64978837/115120845-33235e00-9fcd-11eb-8644-b87c9b011515.png)

![Screenshot from 2021-04-17 21-44-14](https://user-images.githubusercontent.com/64978837/115120848-361e4e80-9fcd-11eb-9865-ae1d42d20763.png)

2021-04-18 04:01 UTC, jennydaman requested changes
The objective of the `pf4` branch is a rewrite, upgrading from Patternfly 3 to Patternfly 4 elements. More technically, we want to replace all imports from `patternfly-react` with components from `@patternfly/react-core`.

Patternfly 4's `FormControl` supports custom icons. See the documentation: https://www.patternfly.org/v4/components/form-control

You should create a reusable component, say `<PasswordFormControl />`, so that code can be reused between sign up and login pages.

2021-04-18 04:04 UTC, somya51p commented
@jennydaman Okay, I will change it. Thanks for the review.

2021-04-19 16:19 UTC, somya51p commented
> The objective of the `pf4` branch is a rewrite, upgrading from Patternfly 3 to Patternfly 4 elements. More technically, we want to replace all imports from `patternfly-react` with components from `@patternfly/react-core`.
> 
> Patternfly 4's `FormControl` supports custom icons. See the documentation: https://www.patternfly.org/v4/components/form-control

@jennydaman As the eye icon is not available as custom icons. Can u suggest what shall I do or shall I replace entire form with the `LoginForm` of `PatternFly`?

2021-04-20 20:10 UTC, jennydaman commented
The entire form should be replaced.

Didn't you find the icon here?
https://github.com/FNNDSC/ChRIS_ui/pull/238/files#diff-44dd688fe0b3b6588c137bf5e8ba2a5ae6540bedf87a69ea544de58dd5212a6bR20

2021-04-28 08:21 UTC, somya51p commented
@jennydaman Please review the changes I have made. 

![Screenshot from 2021-04-28 13-50-58](https://user-images.githubusercontent.com/64978837/116371254-dc1d5480-a828-11eb-8f16-67018f9e3919.png)
![Screenshot from 2021-04-28 13-51-06](https://user-images.githubusercontent.com/64978837/116371272-dfb0db80-a828-11eb-8bb8-13f9aa48c277.png)
![Screenshot from 2021-04-28 13-51-18](https://user-images.githubusercontent.com/64978837/116371280-e2abcc00-a828-11eb-98e3-289b9e0eeb12.png)

2021-05-03 11:44 UTC, jennydaman requested changes

2021-05-03 11:44 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
>    handleSubmit(event) {
It would be nice if the password is set to hidden when the user clicks submit.

2021-05-03 11:44 UTC, jennydaman commented on src/components/PasswordValue/index.js
> +import { InputGroup } from 'react-bootstrap';
Is it possible to use a Patternfly component here instead? Ideally, we do not want to mix UI libraries. It should be a future goal to remove `react-bootstrap` from the dependencies.

2021-05-03 11:44 UTC, jennydaman commented on src/components/PasswordValue/index.js
> +  } = props;
there is a lot going on here.

In React, the traditional HTML attributes are usually not used explicitly here. It leads to non-intuitive behavior. Typically we'd want those attributes (e.g. `id`, `className`, `style`) to be spread on the parent returned by `render` e.g.

```javascript
const PasswordValue = ({myCustomProp, ...props}) => {
  return (
    <div {...props}>
      {something myCustomProp ? <div /> ...}
    </div>
  );
};
```

2021-05-03 11:44 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +    this.setState({ hidden: !this.state.hidden });
nitpick: I think it's better style to use the version of `setState` which accepts the function `(prevProps) => {}`

2021-07-02 17:37 UTC, closed without merging