welcome page upgrade
FNNDSC/ChRIS_store_ui pull request #157
Opened 2021-04-17 20:35 UTC by sonylomo

- Changed Icons component to pf4.
- Destructured some props.

2021-04-19 02:23 UTC, jennydaman requested changes
Looks good for the most part. However, for this project we're using `yarn` not `npm` so please

```shell
git rm package-lock.json
```

2021-04-19 07:16 UTC, jennydaman requested changes

2021-04-19 07:16 UTC, jennydaman commented on src/components/Welcome/components/WelcomeFeature/WelcomeFeature.js
> +const WelcomeFeature = ({img, name}) => (
As a practice it's good to also accept

```javascript
const WelcomeFeature = ({img, name, ...props}) => (
```

And then spread `{ ...props}` on the parent element returned.

2021-04-19 18:27 UTC, sonylomo commented on src/components/Welcome/components/WelcomeFeature/WelcomeFeature.js
> +const WelcomeFeature = ({img, name}) => (
I realized that I hadn't made changes to `WelcomeCategories` component. I've also implemented the changes you requested.

2021-04-20 20:14 UTC, jennydaman requested changes
For flexibility, the parent returned by `render` should be attribute-less and spread `{...props}` so that attributes can be passed from the client. Usually useful for setting a class.

2021-04-20 20:14 UTC, jennydaman commented on src/components/Welcome/components/WelcomeCategory/WelcomeCategory.js
>    <Card className="welcome-category">
Consider adding a wrapper `<div {...props}>`

2021-04-20 20:14 UTC, jennydaman commented on src/components/Welcome/components/WelcomeFeature/WelcomeFeature.js
>    <div className="welcome-feature">
Consider adding a wrapper `<div {...props}>`

2021-04-21 12:21 UTC, jennydaman requested changes
Spacing between elements and responsive centering is missing. Could you take a look?

![screenshot](https://user-images.githubusercontent.com/20404439/115552695-9685e800-a27a-11eb-811d-1771ce3eee05.png)

2021-04-21 18:13 UTC, sonylomo commented
Sorry I missed that - it's coz of the added <div> wrapper.

2021-04-23 04:15 UTC, jennydaman approved these changes

2021-04-23 04:16 UTC, merged