Updated plugin body
FNNDSC/ChRIS_store_ui pull request #161
Opened 2021-04-18 11:26 UTC by zrthxn

Fixes: #160 

Handle any Promise rejection by `fetchPluginData()` in the `componentDidMount` lifecycle method of `src/components/Plugin/Plugin.js`. Return a 404 screen if after loading there is no pluginData.

![Screenshot (54)](https://user-images.githubusercontent.com/35369637/115143602-03746480-a066-11eb-861b-711934dfd88a.png)

## Overview of changes
These fixes focus on making the Plugin component more relevant and useable.
1. Fetching repository data from Github public API to use for populating relevant fields.
2. Fetch README from public repo community profile from Github public API to display as plugin documentation.
3. Display README as Markdown using package [marked](https://www.npmjs.com/package/marked).
4. Fixed many layout issues in PluginBody and made the component slightly more mobile friendly.

### Images
![Screenshot (52)](https://user-images.githubusercontent.com/35369637/115142766-29e3d100-a061-11eb-8142-0d67cd0916d2.png)

## Work in Progress
With further discussion more changes will be added according to what direction is to be taken. 
This is not the final state of this work.

2021-04-18 11:32 UTC, zrthxn commented
Fixes: #160 

Handle any Promise rejection by `fetchPluginData()` in the `componentDidMount` lifecycle method of `src/components/Plugin/Plugin.js`. Return a 404 screen if after loading there is no pluginData.

![Screenshot (54)](https://user-images.githubusercontent.com/35369637/115143602-03746480-a066-11eb-861b-711934dfd88a.png)

2021-04-19 03:03 UTC, jennydaman commented
Awesome. I'll review when you say it's ready to go.

We've had several discussions about how best to address the README issue, this approach has a good effort-to-reward solution. We can think about handling other issues (like READMEs for outdated plugins) in the future.

2021-04-19 06:34 UTC, zrthxn commented
There's a slight problem though, that most existing plugins have readme files in .rst format which doesn't show up perfectly as Markdown.

2021-04-19 09:56 UTC, zrthxn commented
Added temporary support for .rst files but the rendered output doesn't look great. So currently treating it as Markdown.

2021-04-19 20:42 UTC, zrthxn commented
@jennydaman You can review this now

2021-04-20 20:25 UTC, jennydaman commented
@zrthxn RST is out of scope, don't worry about it

2021-04-20 20:34 UTC, jennydaman requested changes

2021-04-20 20:34 UTC, jennydaman commented on src/components/Plugin/Plugin.js
> +      return Promise.reject(e);
I think you should just not bother catching here if the exception cannot be handled by this function.

I am not sure it makes sense to `return Promise.reject(e)`, especially not in an `async` block

2021-04-20 20:34 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +      .split('').reverse().join('')   // Reverse the URL
This is very inefficient.

Since README is being fetched by URL, could you try checking its `Content-Type`?

2021-04-21 08:39 UTC, zrthxn commented on src/components/Plugin/Plugin.js
> +      return Promise.reject(e);
Returning a rejected Promise here is so that the catch error can be "bubbled up" to the componentDidMount where this function is called and then it can be handled by the catch block there. This way all errors can be handled in the same place (i.e. the catch block in the CDM method)

https://github.com/FNNDSC/ChRIS_store_ui/blob/63d9b5d84e1620048721abe54d059c42b41b2f02/src/components/Plugin/Plugin.js#L48-L52

If this seems like an anti-pattern then the errors can be handled where they happen.

2021-04-21 09:05 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +      .split('').reverse().join('')   // Reverse the URL
Unfortunately the downloads from raw.githubusercontent.com (which is where the `download_url` points to) do not supply the appropriate Content Type header for README files. Its always `text/plain; charset=utf-8`.

2021-04-22 04:47 UTC, jennydaman commented on src/components/Plugin/Plugin.js
> +      return Promise.reject(e);
`return` _typically_ implies that the state is expected and that the data is sane. The safer way of handling errors would be to let exceptions be thrown and caught. To handle this exception, wouldn't you need something like

```javascript
let result = await fun();
if (result instanceof Promise.reject) ...
```

2021-04-22 04:58 UTC, jennydaman commented on src/components/Plugin/Plugin.js
> +      return Promise.reject(e);
In other words, exceptions mean "something unexpected happened, and the app's state (data) doesn't make sense anymore." Thus when a function does not throw an exception, it means "everything worked as expected." If you catch an exception without being able to restore the state (in this case, set `loading: false` and get stars) then the component won't know that something went wrong, and it'll keep trying to work on bad data (an unexpected `Promise.reject` object) leading to more data/state corruption.

Catch an exception if:

- the state can be corrected somehow (e.g. ok, something went wrong, let's show an error message and stop making things worse)
- within the function's scope it can handle the exception in a way that is better than how its parent might handle the exception
- we can enhance the exception before rethrowing it with extra information from the current scope

2021-04-22 05:41 UTC, jennydaman requested changes

2021-04-22 05:41 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +    const url = (await
Please flatten this...

Or, you might be interested in "pipe syntax." Currently it is just a [proposal to the language](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Pipeline_operator), but there are NPM packages implementing the functionality (look them up) --- and you could implement it yourself in 10-20 lines of code.

2021-04-22 05:41 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +      setReadme(marked(await file.text()))
I would recommend moving `setReadme` outside of `fetchReadme`.

Doing so adheres to "functional programming" and has a few advantages:

- the function `fetchReadme` becomes "stateless," i.e. without side effects — fewer bugs
- a stateless function which processes data deterministically is easier to test (you can write unit tests to test the functionality of fetching a README without having to test how it renders the README into JSX)
- separate data processing logic (the "model") from logic related to updating the UI (the "controller") see [MVC pattern](https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller). Separation makes it easier to replace one part (say, replacing the visual layer without changing how the data processing logic works, as we're trying to do right now with the Patternfly 3 -> 4 upgrade) easier.

2021-04-22 05:41 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +    if (expectRepoName)
Did you `yarn run lint`?

2021-04-22 05:41 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +        console.error(error)
https://github.com/FNNDSC/ChRIS_store_ui/pull/161#discussion_r618080232

2021-04-22 05:41 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +                              { readme ? <div dangerouslySetInnerHTML={{ __html: readme }}></div> : null }
Please see the security warning about the `marked` package.
https://www.npmjs.com/package/marked

2021-04-22 09:54 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +    if (expectRepoName)
Yes and it didn't give me any problems related to this?
![Screenshot (56)](https://user-images.githubusercontent.com/35369637/115694757-cb7b6300-a37e-11eb-82b2-15f8edad8023.png)

2021-04-22 09:54 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +                              { readme ? <div dangerouslySetInnerHTML={{ __html: readme }}></div> : null }
Added sanitization on the HTML generated by marked. Although I'm not completely sure that this would've introduced an XSS vulnerability since we are getting the content from Github and I think it does sanitize the README. Not sure though.

2021-04-22 10:07 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +      setReadme(marked(await file.text()))
Moved `setReadme` outside of `fetchReadme`
Moved `setRepoData` outside of `fetchRepoData`

2021-04-22 10:44 UTC, zrthxn commented on src/components/Plugin/Plugin.js
> +      return Promise.reject(e);
Alright I understand. It was wrong to throw the same Exception twice. I've now switched to handling the errors where they happen, if they can be, otherwise let the function reject the Promise.

2021-04-22 11:09 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +    const url = (await
I didn't know about that, I'll look into it. Although in this case it was simpler to just refactor a bit.

2021-04-22 16:02 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +    if (expectRepoName)
I must be getting eslint configs confused across different projects, sorry...

2021-04-22 16:03 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +                              { readme ? <div dangerouslySetInnerHTML={{ __html: readme }}></div> : null }
Github would sanitize markdown when they render it themselves, but they serve it as-is when you request the raw `.md` file.

2021-04-22 16:09 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +          setReadme(marked(file))
Security paranoia: I would call `sanitize` somewhere around here. That way, the untrusted data is never stored in state. (Also marginally more efficient in situation where state can be set preemptively, i.e. before `render()`.)

2021-04-22 17:03 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +          setReadme(marked(file))
That does make sense, also prevents accidental usage of unsafe html.

2021-04-23 04:29 UTC, jennydaman requested changes

2021-04-23 04:29 UTC, jennydaman commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +import { Grid, Nav, NavItem, TabContainer, TabContent, TabPane } from 'patternfly-react';
Would you try converting this page to use components from `@patternfly/react-core`?

2021-04-23 15:28 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.js
> +import { Grid, Nav, NavItem, TabContainer, TabContent, TabPane } from 'patternfly-react';
Done

2021-04-24 08:04 UTC, jennydaman approved these changes
I still think [`src/components/Plugin/components/PluginBody/PluginBody.js`](https://github.com/FNNDSC/ChRIS_store_ui/pull/161/files#diff-198b4e0e2d3645575d568b23f6cad63b62fdd14d3c3c6e790059c8ec1ee3915f) should be split up to conform with a MVC pattern. Nonetheless, this feature is very important and I think you did a good job with what's here.

Do you want it to be merged now and leave refactoring as subsequent work?

2021-04-24 08:09 UTC, zrthxn commented
For the moment I think it's working well enough to be tested. But if you'd like to get it completed then I don't mind. About MVC, I think that might be overworking something that doesn't need that level of complication?

2021-04-24 08:11 UTC, jennydaman commented
Good point. I suppose getting READMEs from Github is a solution "for the time being" anyways, since eventually we'll need to implement a better solution which takes into account outdated plugins and plugins hosted on other websites.

Let me do some more testing and then I will be happy to merge.

2021-04-24 08:15 UTC, merged

2021-04-24 08:28 UTC, zrthxn commented
A few things I think could be done to support other Git platforms/providers and handle versions. 
1. Support a limited set of git platforms, the most popular ones like Github, gitlab, bitbucket etc. Since it would be realistically impossible to support every single one. 
2. Instead of using the git repository, use DockerHub to manage readme/documentation since it's a central platform and any image that can be pulled by tag would have to be there. 
3. Resolve the issues with plugins getting outdated after discussing a bit more.