Added CSS modules
FNNDSC/ChRIS_store_ui pull request #162
Opened 2021-04-21 06:54 UTC by somya51p

Added CSS modules. @jennydaman @mairin  Please review the PR and suggest changes if any.
This PR is associated to issue number #151.

2021-04-23 03:22 UTC, jennydaman reviewed
A lot of good work here. Let me know what you think about [`@patternfly/react-styles`](https://www.npmjs.com/package/@patternfly/react-styles)

2021-04-23 03:22 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +            <div className={`row`}>
Would it be possible to incorporate [`@patternfly/react-styles`](https://www.npmjs.com/package/@patternfly/react-styles)?

2021-04-23 03:22 UTC, jennydaman commented on src/components/Dashboard/components/DashTeamView/DashTeamView.js
> +                  <Table.DropdownKebab id={styles['myKebab']} pullRight>
It might be useful to change this ID to a class.

2021-04-23 07:39 UTC, somya51p commented on src/components/Dashboard/components/DashTeamView/DashTeamView.js
> +                  <Table.DropdownKebab id={styles['myKebab']} pullRight>
@jennydaman Yeah sure I will replace the ID with class. 

But for [@patternfly/react-styles](https://www.npmjs.com/package/@patternfly/react-styles) not much documentation is available. It's difficult to go for that. But if you wish I can give it a try.

2021-04-23 17:50 UTC, somya51p commented
@jennydaman Please have a look. I have converted `id` to `classname` where id were not involved in further code. Please review and suggest changes if any.

2021-04-24 08:36 UTC, jennydaman commented
@somya51p I just merged a pretty big PR, #161 — it's created some conflicts. You did not give me write access to your fork, so could you try to resolve the merge conflicts?

After that, let's merge this PR. We can save [@patternfly/react-styles](https://www.npmjs.com/package/@patternfly/react-styles) to be work for another day. I was unable to find much documentation on it either, but it's probably something that could be figured out using an IDE's autocompletion.

2021-04-24 09:46 UTC, somya51p commented
@jennydaman I have resolved the conflicts. You may have a look!

2021-04-25 04:20 UTC, jennydaman commented
Did something happen between your comment and the force push? The conflicts are still there.

2021-04-25 04:43 UTC, somya51p commented
@jennydaman Resolved them all. I don't know what happened, maybe I did something by mistake. I apologize from my end :)

2021-04-25 05:06 UTC, jennydaman commented on src/components/CreatePlugin/CreatePlugin.js
> +            <div className={`row`}>
Continuing in https://github.com/FNNDSC/ChRIS_store_ui/issues/167

2021-04-25 05:48 UTC, jennydaman requested changes

2021-04-25 05:48 UTC, jennydaman commented on src/components/SignIn/SignIn.js
>  import { Form, Alert, AlertActionCloseButton } from '@patternfly/react-core';
Does not compile. The merge conflict resolution should remove `Alert` and `Button` imported from `patternfly-react`

#142 #165

2021-04-25 05:51 UTC, somya51p commented on src/components/SignIn/SignIn.js
>  import { Form, Alert, AlertActionCloseButton } from '@patternfly/react-core';
@jennydaman made changes. Please review.

2021-04-25 06:48 UTC, jennydaman commented
@somya51p Big sorry for more conflicts! It really seems like we're going back and forth, though these new changes were vital. I've forward-ported some features from master, such as #139 and #119

2021-04-25 07:35 UTC, somya51p commented
@jennydaman I have resolved the conflicts now. Please have a look.

2021-04-25 10:10 UTC, jennydaman requested changes

2021-04-25 10:10 UTC, jennydaman commented on src/components/Navbar/Navbar.js
> +      className={styles['login-button']}
![image](https://user-images.githubusercontent.com/20404439/115989442-6432fe00-a58c-11eb-874c-93eec78692b2.png)

Color is wrong, could have something to do with the patternfly CSS variables.

2021-04-25 10:10 UTC, jennydaman commented on src/components/Welcome/components/WelcomeCategories/WelcomeCategories.js
> +    <div className={styles['welcome-categories']}>
![image](https://user-images.githubusercontent.com/20404439/115989510-bd9b2d00-a58c-11eb-9df4-91f978911723.png)

Styling incorrect.

Hmm, reminds me of https://github.com/FNNDSC/ChRIS_store_ui/pull/157#pullrequestreview-640998000

Not sure if it's a bug in the CSS module or incorrect merge conflict resolution.

2021-04-26 18:25 UTC, somya51p commented on src/components/Welcome/components/WelcomeCategories/WelcomeCategories.js
> +    <div className={styles['welcome-categories']}>
@jennydaman I have tried many things but don't know why this is happening in CSS modules. If I am using normal CSS then the cards are responsive so the merge conflict resolution issue might not be there.

2021-04-27 15:19 UTC, somya51p commented
@jennydaman You may have a look. We are using `button` components from two different files so CSS modules are not responding if we are using that. I have removed CSS modules for the `Navbar` and `Welcomecategory.` Now it is looking as before. And the problem CSS modules are causing I will soon try to rectify. I request you to merge at least these changes, I will send another PR for those changes else merge conflicts occur.

2021-05-05 17:16 UTC, somya51p commented
@jennydaman Please review the changes once. And if possible merge the PR, I will send another PR for the `WelcomeCategory.jsx` and `button` to change to CSS modules.

2021-05-06 17:25 UTC, jennydaman requested changes

2021-05-06 17:25 UTC, jennydaman commented on src/components/Dashboard/components/DashTeamView/DashTeamView.js
> +                  <Table.DropdownKebab className={styles['myKebab']} pullRight>
this class doesn't exist, let's delete it.

2021-05-06 17:25 UTC, jennydaman commented on src/components/Navbar/components/Search/Search.js
> +                onMouseDown={(e) => {
Your branch contains old commits, could you make sure you've merged `pf4`?

https://github.com/FNNDSC/ChRIS_store_ui/pull/171/files#diff-9a24940a3a0dc9528f50eadd792809d7cf70188d676001f94d7d87d826280a90R78

2021-05-06 18:09 UTC, somya51p commented on src/components/Navbar/components/Search/Search.js
> +                onMouseDown={(e) => {
@jennydaman I have made the changes suggested by you and I have rebased my branch with the `pf4` again. Just have a look, now I think everything is up-to-date.

2021-05-06 22:21 UTC, jennydaman approved these changes
A monumental advancement, great job @somya51p

2021-05-06 22:21 UTC, merged

2021-05-08 07:56 UTC, DivyanshiSingh commented on src/components/SignIn/SignIn.js
> +                  className={styles['signin-login-btn']}
@jennydaman @somya51p wrong code merged while resolving conflicts