Upgraded Card from PF3 to PF4
FNNDSC/ChRIS_store_ui pull request #175
Opened 2021-04-26 09:16 UTC by DivyanshiSingh

Fixes: #101 
1) Card feature is upgraded to pf4 in all files.
@jennydaman please review and let me know the required changes.

2021-04-26 14:07 UTC, jennydaman requested changes
Layout and positioning of options vdots are off.

![image](https://user-images.githubusercontent.com/20404439/116096184-11824080-a677-11eb-89e8-681bb5246a36.png)

For the future, it's better not to change code style e.g. single-quotes to double quotes — it is a huge merge conflict risk. There is an open issue for this: #168

2021-04-26 14:19 UTC, DivyanshiSingh commented on src/components/Dashboard/Dashboard.js
> +          <Grid className="container">
Ok, @jennydaman I will make the required changes.

2021-04-28 16:25 UTC, DivyanshiSingh commented on src/components/Dashboard/Dashboard.js
> +          <Grid className="container">
done please review

2021-05-03 12:09 UTC, jennydaman approved these changes
Sorry for the wait @DivyanshiSingh 
Everything is looking good to me. Keep in mind for the future that you should try suppressing your IDE from reformatting the code style of entire files. It can lead to merge conflicts.
(Unless, that is, whatever future task you're working on is #168)

2021-05-03 12:09 UTC, merged

2021-05-03 12:22 UTC, DivyanshiSingh commented
Ok sure, I will keep that in check.