PF4 plugins revamp
FNNDSC/ChRIS_store_ui pull request #176
Opened 2021-04-26 11:49 UTC by sonylomo

Fixes issue #101 
- Upgraded from class components to functional components.
- Upgraded from pf3 to pf4.

2021-04-26 14:11 UTC, jennydaman commented
Hey @sonylomo there was a major overhaul to `Plugins.js` in #171 which unfortunately breaks most of this PR

2021-04-26 16:47 UTC, sonylomo commented
Yes, I've been working to resolve them.

2021-05-04 17:02 UTC, jennydaman requested changes

2021-05-04 17:02 UTC, jennydaman commented on src/components/Plugins/components/PluginItem/PluginItem.js
> +  id,
We should rename `id`i and `tittle` because they shadow HTML attribute names.

2021-05-06 07:51 UTC, sonylomo commented on src/components/Plugins/components/PluginItem/PluginItem.js
> +  id,
I've changed them to `pluginId` and `pluginTitle`.

2021-05-06 21:54 UTC, jennydaman requested changes

2021-05-06 21:54 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +            <DropdownButton
When `pluginList` is `null` (for instance, if the backend is unreachable) the page crashes.

2021-05-12 18:55 UTC, jennydaman commented
@sonylomo let me know on Slack if you need help rebasing.

2021-05-20 14:33 UTC, jennydaman requested changes

2021-05-20 14:33 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +  let history = useHistory();
Why not `const history`?

2021-05-20 14:33 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +        onChange={(val) => setPasswordConfirm(val)}
I don't think the arrow expression is necessary here.

2021-05-20 14:33 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +    setError({
I think we should flatten this object, i.e. replace with two state variables `errorMessage` and `errorControls`.
Moreover, the types are inconsistent -- `controls` is expected to be a list.

2021-05-20 14:33 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +        setLoading(false);
Could we add an error message to the UI here too? Maybe that the network request failed?

2021-05-20 14:33 UTC, jennydaman commented on src/components/Navbar/Navbar.module.css
> +.login-button .other-button{
Is the filename `Navbar.module.css` correct?

2021-05-21 09:06 UTC, sonylomo commented on src/components/Navbar/Navbar.module.css
> +.login-button .other-button{
It should be deleted.

2021-05-22 10:22 UTC, sonylomo commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +    setError({
Both error controls and messages have to be updated at the same time in the return statements like these:
`if (!password) {
      return setError({
        message: "Password is required",
        controls: ["password"],
      });
    }`

I don't think there's another way of doing this with the `error` object separated into 2 states. Unless you know another way 🤔.

2021-05-22 11:48 UTC, sonylomo commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +        setLoading(false);
Should I use notification or error handling on the input fields?

2021-05-26 13:07 UTC, jennydaman requested changes

2021-05-26 13:07 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +        helperText="Enter you email"
Would you fix this typo? "Enter your email"

2021-05-26 13:07 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +          controls: ["username", "email", "password"],
In the event of a network request failure, we should probably have the `controls` array be empty, to convey that it is not an error of user input.

2021-05-26 13:07 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +        setLoading(false);
https://github.com/FNNDSC/ChRIS_store_ui/blob/ec5e30492c95f8c7933c8d6ef6b3563304988c61/src/components/Dashboard/Dashboard.js#L29

2021-05-26 13:07 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +    setError({
Do they have to be coupled or is it that it "just makes sense" to have them coupled?

Logically I think it'd be fine for us to allow an error message to be displayed without any fields turning red, or have fields turn red without an error message being displayed. While these situations wouldn't make sense (or at least are not friendly to the user) I think it makes development easier.

Though this is subjective, if you like how it is now or have your own idea, please do as you think best.

2021-05-26 19:31 UTC, sonylomo commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +        onChange={(val) => setPasswordConfirm(val)}
I think the arrow function is necessary for updating `PasswordConfirm` state with the input value.

2021-06-02 13:57 UTC, jennydaman commented on src/components/FormInput/index.js
> +      helperTextInvalid={errorMessage && errorControls && errorControls.includes(fieldName) ? errorMessage: null}
What was the rationale for this change?
Could you describe to me what the purpose of `errorControls` is and why it's necessary?

Maybe we can simply have four state variables, `errorUsername`, `errorPassword`, `errorPasswordConfirm`, `errorEmail`, ... and no `errorControls`

2021-06-03 02:35 UTC, sonylomo commented on src/components/FormInput/index.js
> +      helperTextInvalid={errorMessage && errorControls && errorControls.includes(fieldName) ? errorMessage: null}
Since the `errorControls` point to the field names i.e username, email, password, etc, I thought that it'd be reasonable to check if it's True. I also agree that it'd be better to separate the controls into 4 states.

2021-06-07 08:28 UTC, jennydaman commented on src/components/FormInput/index.js
> +      helperTextInvalid={errorMessage && errorControls && errorControls.includes(fieldName) ? errorMessage: null}
Well `helperText` is one simple variable, could `helperTextInvalid` be coded up in the same way?

2021-06-07 08:35 UTC, jennydaman commented on src/components/FormInput/index.js
> +      helperTextInvalid={errorMessage && errorControls && errorControls.includes(fieldName) ? errorMessage: null}
Simple as (theoretically) `helperTextInvalid=errorUsername`

> I can't reset the states of `errorUsername`, `errorPassword`, `errorPasswordConfirm`, `errorEmail` etc, after they've shown an error.

Why not? Could it be done in [`handleStoreLogin`](https://github.com/FNNDSC/ChRIS_store_ui/pull/176/files/5ea0f78b7498ed644c023af5398720330659295a#diff-bf517181be23941f250cd1ab597ce0e352b2d7aae0b14ace7b7317e51d92fd14R91)?

2021-06-22 05:47 UTC, jennydaman requested changes

2021-06-22 05:47 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +    setPluginStar(pluginId, undefined);
a nitpick: typically `null` and `undefined` have the same effect, but in situations like this, it's better to set values as `null`. `null` denotes an empty value, and usually implies that the developer has set the variable's value to null intentionally. Sticking to such a practice makes it so that it's easier to identify logical errors when `undefined` pops up.

2021-06-22 05:47 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +    return starsByPlugin[plugin.id] !== undefined;
If you do take the advice above and use `null` instead of `undefined`, be sure to also change the strict equality check here.

2021-06-22 05:47 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +            errorUsername.includes("username") ? "error" : "default"
I still do not understand why this approach is being used.

Here, `errorUsername`, `errorPassword`, etc..., are practically boolean variables. It do not think these are necessary.

My previous advice was to have four variables, `errorUsername`, `errorEmail`, `errorPassword`, `errorPasswordConfirm`. As we've discussed, having only one variable for `errorMessage` is poor program design because:

1. the view (in the context of the MVC pattern) should not care about what is being displayed. The view should allow for multiple error messages to be shown, e.g. both messages "Username is invalid" and "Password is empty" should be allowed to be shown at the same time. (If you think this is poor UX, then it is the model's responsibility to not set multiple error messages.)
2. in your implementation, `errorMessage` is serving one of four roles (showing error for username box, showing error for email box, showing error message for password box, showing error message for password confirm box). Which of these roles it serves is set by four other variables. So why not have one variable per role?

I think some of this confusion comes from how `src/components/FormInput/index.js` was originally implemented. Don't be scared to stray from original implementations (if you find them disagreeable).

Can you answer this question: "what is the purpose of the prop `errorControls` to `FormInput` (why do we need it)?"  In the 30 lines,  to me it seems like it serves no purpose.

This is also somewhere where documenting your code can be helpful. Every prop to a component should be documented. In well-documented code, I wouldn't have to ask such a question.

See if you can implement something like this. First, in pseudocode:

```
Does errorUsername have a value?
  If true, set validated="error" and helperText=errorUsername
  Else, set validated="default"
```

Suggested code:

```jsx
<FormInput
  formLabel="username"
  helperText="Enter your username"
  inputType="text"
  autoFocus={!isTouchDevice}
  onChange={(val) => setEmail(val)}
  errorMessage={errorUsername}
/>
```

Inside the code for `FormInput` it will decide: if `errorMessage` has a value, then pass the props `validated="error"` and `helperText=errorUsername` to `FormGroup`.

2021-06-22 05:47 UTC, jennydaman commented on src/components/FormInput/index.js
> +  } = props;
As aforementioned, I recommend adding documentation for all of these props. Any prop which seems to serve no purpose, or serve little purpose, should be removed. In particular, I find it strange that `fieldId`, `id`, and `fieldName` are usually set to the same value (like `"username"`)

Notice `id` is not being used.

I don't recommend `className`. Instead, spread the extra props on the parent.

```jsx
const FornInput = ({formLabel, fieldId, validationState, ...props}) => {
  return (<div ...props> [awesome code here] </div>)
}
```

2021-06-22 05:47 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +            {/* Plugin List Body*/}
Comments are good when informative, but I do not think this is informative.

2021-06-30 15:19 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +    setPluginStar(pluginId, undefined);
@sonylomo you've marked this as resolved but did not make a change, does this imply that your software design choice is to use `undefined`?

2021-07-02 13:50 UTC, sonylomo commented on src/components/Plugins/Plugins.js
> +    setPluginStar(pluginId, undefined);
@jennydaman, I hadn't commited the changes yet. I ran into another issue, for some reason the inputs are being registered as 2 values: a synthetic event and string (realized it after console logging). I've been trying to figure out why; maybe it's Patternfly. I've remade the Developer Signup component from scratch a couple of times but it still didn't work.

2021-07-02 17:37 UTC, closed without merging