Developer Components Upgrade to pf4
FNNDSC/ChRIS_store_ui pull request #182
Opened 2021-05-04 13:45 UTC by sonylomo

Fixes issue #101 

- Changed class components to functional ones.
- Changed from pf3 to pf4
- Upgraded outdated react-bootstrap components.

2021-05-04 17:39 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +  const disableControls = loading;
We should take this out

2021-05-04 17:39 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/DeveloperSignup.js
> +  const disableControls = loading;
We should take this out

2021-05-04 17:39 UTC, jennydaman commented on src/components/Navbar/Navbar.js
> +  const location = useLocation()
This is a good change. It might make prerendering or SSR easier too.

2021-05-04 17:39 UTC, jennydaman commented on src/components/Plugins/Plugins.js
> +import { DropdownButton, Dropdown } from 'react-bootstrap';
Do you think we can use Patternfly components here, replacing `react-boostrap`?

2021-05-04 20:40 UTC, sonylomo commented on src/components/Plugins/Plugins.js
> +import { DropdownButton, Dropdown } from 'react-bootstrap';
Yeah I can.

2021-05-04 20:50 UTC, sonylomo commented on src/components/Navbar/Navbar.js
> +  const location = useLocation()
Thanks.

2021-05-06 07:41 UTC, sonylomo commented
I've used id to style the `sort by` button to remain on the right side of the page. I tried using classname but I had to add `!important` on every style for it to work. I hope it's ok.

2021-05-06 19:02 UTC, jennydaman requested changes

2021-05-06 19:02 UTC, jennydaman commented on src/components/Plugins/Plugins.css
> +  list-style: none !important;
This shouldn't be necessary, it should be handled by Patternfly. We should investigate. Maybe transpile config is wrong, maybe an update would help?

2021-05-06 20:42 UTC, sonylomo commented on src/components/Plugins/Plugins.css
> +  list-style: none !important;
I've tried to update but it hasn't changed.

2021-05-06 21:30 UTC, jennydaman commented on src/components/Plugins/Plugins.css
> +  list-style: none !important;
Found it! `patternfly.css` is being left out. Maybe we should add the line below to `index.js`?

```javascript
import '@patternfly/patternfly/patternfly.css';
```

2021-05-07 09:05 UTC, sonylomo commented on src/components/Plugins/Plugins.css
> +  list-style: none !important;
cool

2021-05-07 20:01 UTC, jennydaman approved these changes

2021-05-07 20:02 UTC, merged