Addressing issue no #198
FNNDSC/ChRIS_store_ui pull request #200
Opened 2021-05-20 16:28 UTC by praguru14

Have separated isTouchDevice form DeveloperSignup.js

2021-05-20 19:12 UTC, jennydaman requested changes

2021-05-20 19:12 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/isTouchDevice.js
> +import ChrisStore from '../../../../store/ChrisStore';
Hmm, none of these imports seem to be used below.

2021-05-21 04:23 UTC, praguru14 commented on src/components/Developers/components/DeveloperSignup/isTouchDevice.js
> +import ChrisStore from '../../../../store/ChrisStore';
Hi I have removed the said imports , thanks.

2021-05-26 02:00 UTC, jennydaman commented on src/components/Developers/components/DeveloperSignup/isTouchDevice.js
> +import ChrisStore from '../../../../store/ChrisStore';
They are still present.

2021-07-21 19:19 UTC, closed without merging