Replace shortened links with real links
FNNDSC/ChRIS_store_ui pull request #201
Opened 2021-05-21 13:30 UTC by NikhilSharma03

This PR fixes #199

## Desciption
 
Updated the outdated link in the Instructions.js to the provided link.

2021-05-26 02:05 UTC, jennydaman requested changes
Not all of the links are the same, would you double-check them?

2021-05-26 02:05 UTC, jennydaman commented on src/components/Developers/components/Instructions/Instructions.js
> +              <a href="https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Quickstart">simple <strong>fs</strong> plugin</a>
This is supposed to be a link to https://github.com/FNNDSC/pl-simplefsapp

2021-05-26 02:05 UTC, jennydaman commented on src/components/Developers/components/Instructions/Instructions.js
> +              <a href="https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Quickstart">simple <strong>ds</strong> plugin</a>
This is supposed to be a link to https://github.com/FNNDSC/pl-simpledsapp

2021-05-26 04:43 UTC, NikhilSharma03 commented
@jennydaman .I have updated. Can you check if there's any wrong link?

2021-05-26 13:16 UTC, jennydaman requested changes

2021-05-26 13:16 UTC, jennydaman commented on src/components/Developers/components/Instructions/Instructions.js
> +                    href="https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Quickstart"
Hmm, it's kind of silly for a bulleted list to show two links which go to the same place.
On review, the `<ul>` doesn't seem useful. Perhaps it should be removed altogether.

2021-05-26 13:16 UTC, jennydaman commented on src/components/Developers/components/Instructions/Instructions.js
> +              consult the <a href="https://github.com/FNNDSC/cookiecutter-chrisapp/wiki">wiki</a> to learn how to register it to
Would you link to the specific page, https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Register-a-new-plugin-app-with-the-ChRIS-store-API

2021-05-27 08:31 UTC, NikhilSharma03 commented on src/components/Developers/components/Instructions/Instructions.js
> +                    href="https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Quickstart"
@jennydaman Should I deleted <ul> . If that's so then I guess we can remove its parent ( <h3> ) then.

2021-07-30 14:46 UTC, closed without merging