Major Refactoring
FNNDSC/ChRIS_store_ui pull request #207
Opened 2021-05-26 10:01 UTC by zrthxn

Summary
- Removed almost all PF3 components, one file remains.
- Change all React `.js` files to `.jsx`

Todo
- Remove the remaining PF3 components and uninstall

2021-05-28 20:02 UTC, zrthxn commented
@jennydaman Completed PF3 removal.

2021-06-14 07:16 UTC, jennydaman requested changes

2021-06-14 07:16 UTC, jennydaman commented on src/components/Developers/components/CopyToClipboard/CopyToClipboard.jsx
> +  <d>
Did you mean `<a>`?

2021-06-14 07:20 UTC, jennydaman commented
Crashes after login.

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
>
> Check the render method of `DashPluginCardView`.

2021-06-14 07:32 UTC, zrthxn commented on src/components/Developers/components/CopyToClipboard/CopyToClipboard.jsx
> +  <d>
Oops, that was supposed to be a div!

2021-06-14 07:35 UTC, zrthxn commented
> Crashes after login.
> 
> > Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> > Check the render method of `DashPluginCardView`.

Thats because of the `MessageDialog` component. It'll have to be commented out for the time being until an equivalent works. I've told @sonylomo about it to get something working asap.

2021-06-14 07:43 UTC, jennydaman commented
Oh yeah, I was just digging at that. So what was the way forward with fixing the `MessageDialog` component, what's @sonylomo's involvement?

2021-06-14 07:47 UTC, zrthxn commented
Right now I dont think she's gotten to it. I'll use the Modal in PF4 to build a replacement.

2021-06-14 08:17 UTC, zrthxn commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +import { CardTitle, CardBody, Card } from "@patternfly/react-core";
Done

2021-06-16 02:03 UTC, jennydaman commented
The project has a different error now. When clicking on a plugin card in `/dashboard` I get

> Unhandled Rejection (TypeError): pluginData is undefined
> componentDidMount
> src/components/Plugin/Plugin.jsx:60

I merged master to resolve merge conflicts. This did not change any of the files.
To be certain, this bug exists in e350365afe48643829f329ee4429cf30e36c41bf

2021-06-16 19:46 UTC, jennydaman requested changes

2021-06-16 19:46 UTC, jennydaman commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +                <Link to={`/plugin/${plugin.name}`}>{plugin.name}</Link>
I found the error.

Here, the URL is being set to something like `chrisstore.co/plugin/pl-example`.

In [`src/components/Plugin/Plugin.jsx:fetchPluginData()`](https://github.com/zrthxn/ChRIS_store_ui/blob/109f28357adee3e58b80f9c8ef546ef33b0a5c13/src/components/Plugin/Plugin.jsx#L121) the function is expecting an integer (plugin ID), not plugin name.

Three comments: first, the quickest fix here would be to set the URL to something like `chrisstore.co/plugins/7` instead.

Second, I think having plugin name instead of plugin ID in the URL is a better UX. This would require some thinking and an overhaul. Currently, the page `chrisstore.co/plugins/7` shows details about one version of a plugin. We want to create a page `chrisstore.co/plugins/pl-example` which shows details about all plugins with the same name `pl-example`, and perhaps has a "Versions" tab which links to specific plugins by ID.

Third, regardless, `Plugin.jsx` needs refactoring. In `fetchPluginData()` the function catches network exceptions but still goes on to return `undefined` and pollute the state. On network error, the exception should be caught then rethrown.
In `componentDidMount()` state management is done messily. We should change `fetchPluginData()` into a stateless, deterministic function.
In situations where the state does not have the plugin data, we should not fetch the plugin data. Instead we should wait for the state to change.

2021-06-16 20:04 UTC, zrthxn commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +                <Link to={`/plugin/${plugin.name}`}>{plugin.name}</Link>
Sorry I'm late on this. 

For the first two comments, i also think having the name in the url is better. And it'd be good to have it show all versions with the name and a specific version with the ID. The fetching function can check for an integer (or hex in future) ID and if that fails then treat it as a name. 

For the third comment, yes I agree with that. I had done that same thing before, with re-throwing the exceptions but then we had a discussion about how we should only catch if we can handle it then and there.

2021-06-17 00:24 UTC, jennydaman commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +                <Link to={`/plugin/${plugin.name}`}>{plugin.name}</Link>
Would you implement the quick fix, that is, have the plugin ID in the URL?
I would like to merge this PR just to unblock other tasks, such as #209 
Also, please create detailed issues to start the discussion on how we can organize routing and information to support URLs with plugin names.

2021-06-17 00:26 UTC, jennydaman commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +                <Link to={`/plugin/${plugin.name}`}>{plugin.name}</Link>
> The fetching function can check for an integer (or hex in future) ID and if that fails then treat it as a name.
I disagree with "guessing" union types. It is safer to be explicit.

> or hex in the future
What do you mean?

2021-06-17 06:11 UTC, zrthxn commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +                <Link to={`/plugin/${plugin.name}`}>{plugin.name}</Link>
Okay I've done the quick fix for now, the rest of the changes will be in the other PR (like having the name in the URL).

> I disagree with "guessing" union types. It is safer to be explicit.

Then the URL can have something like `/plugin/plugin-name` for the named metas that gets all the versions and `/plugin/p/:id` for fetching one specific one by ID.

> What do you mean?

Maybe with growing plugins integer IDs could be handled as hex numbers, but thats way ahead in the future.

2021-06-17 13:03 UTC, jennydaman commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +                <Link to={`/plugin/${plugin.name}`}>{plugin.name}</Link>
> Then the URL can have something like `/plugin/plugin-name` for the named metas that gets all the versions and `/plugin/p/:id` for fetching one specific one by ID.

Sounds better.

> Maybe with growing plugins integer IDs could be handled as hex numbers, but thats way ahead in the future.

Yeah, way ahead into the future.

2021-06-17 13:26 UTC, jennydaman commented
Regressions

#### "Sort By" menu options leak out

![image](https://user-images.githubusercontent.com/20404439/122403866-b5d48500-cf4c-11eb-9152-2ac1097cd47f.png)

#### Plugin details sidebar overlaps

![image](https://user-images.githubusercontent.com/20404439/122403986-d4d31700-cf4c-11eb-8b0f-3d1cf0ae4ec0.png)

#### Dashboard (after sign-in) CSS flaws

Fix spacing next to revisions pane

![image](https://user-images.githubusercontent.com/20404439/122404380-2d0a1900-cf4d-11eb-9732-dfd6f6f2af95.png)

#### Teammates list are plugins again

This seems new, could you explain what is the intention here?

![image](https://user-images.githubusercontent.com/20404439/122405340-f7196480-cf4d-11eb-96e8-eb0bd6ee559c.png)


#### Get a UI notification error "Failed to get plugin stars" when looking at plugin details while logged in

2021-06-17 13:39 UTC, jennydaman commented
#209 inherits from this branch

2021-06-17 13:39 UTC, closed without merging