Plugins fix
FNNDSC/ChRIS_store_ui pull request #209
Opened 2021-05-27 17:55 UTC by zrthxn

2021-05-31 12:26 UTC, zrthxn commented
![Screenshot (86)](https://user-images.githubusercontent.com/35369637/120192974-79f5ac00-c239-11eb-925e-fea8726739c1.png)

2021-06-04 19:34 UTC, zrthxn commented
![Screenshot from 2021-06-05 00-58-23](https://user-images.githubusercontent.com/35369637/120853890-f372fe80-c599-11eb-96a0-c97dcf8075f0.png)
![Screenshot from 2021-06-05 01-01-27](https://user-images.githubusercontent.com/35369637/120853899-f66def00-c599-11eb-901f-0ae1934a6652.png)

2021-06-05 10:20 UTC, zrthxn commented
![Screenshot from 2021-06-05 15-32-58](https://user-images.githubusercontent.com/35369637/120888388-b2b8cb00-c615-11eb-980b-8da6605414e9.png)

2021-06-14 08:18 UTC, zrthxn commented
Rebased to include changes from [refactoring](https://github.com/zrthxn/ChRIS_store_ui/tree/refactoring) branch

2021-06-17 06:15 UTC, zrthxn commented
Rebased to include changes from [refactoring](https://github.com/zrthxn/ChRIS_store_ui/tree/refactoring) branch

2021-06-30 16:02 UTC, jennydaman requested changes

2021-06-30 16:02 UTC, jennydaman commented on src/components/Plugins/components/PluginItem/PluginItem.jsx
> +    setStarActive(true);
Mixed prop/state manipulation.

Whether the star should be grey or yellow should be determined by either prop alone, there should be no internal manipulation of state for something that is decided by a prop. If it is desirable to have these lines of code, they should be moved to `Plugins.jsx`

That is, the only purpose of `onStarClicked` should be to either:

- toggle `isFavorite` (where the design decision would be, stars are a toggle-type checkbox-like component
- call `rest.onStarClicked()` (where `Plugins.jsx` is responsible for providing the prop `onStarClicked={() => setIsFavorite(!isFavorite)}`

2021-06-30 16:02 UTC, jennydaman commented on src/components/general/CopyURLButton.jsx
> +import { CopyToClipboard } from "react-copy-to-clipboard";
Could you look into https://www.patternfly.org/v4/components/clipboard-copy/

2021-06-30 16:08 UTC, zrthxn commented on src/components/Dashboard/Dashboard.jsx
> +  initialize() {
No, not as such.

2021-06-30 16:15 UTC, zrthxn commented on src/components/Plugin/Plugin.jsx
> +
Do you mean the commented out bits?

2021-06-30 16:15 UTC, zrthxn commented on src/components/Dashboard/components/DashPluginCardView/DashPluginCardView.jsx
> +  toggle = (value, id) => {
Alright will do.

2021-06-30 16:22 UTC, zrthxn commented on src/components/general/CopyURLButton.jsx
> +import { CopyToClipboard } from "react-copy-to-clipboard";
Deleting this single use component.

2021-06-30 16:25 UTC, zrthxn commented on src/components/Developers/components/CopyToClipboard/CopyToClipboard.jsx
> +const CopyToClipboard = ({ clipboardText }) => (
Replacing.

2021-06-30 16:48 UTC, zrthxn commented on src/components/Plugins/components/PluginItem/PluginItem.jsx
> +    setStarActive(true);
The purpose was to make the tooltip disappear after the star was clicked. But I think we can do without that.

2021-07-02 17:31 UTC, jennydaman requested changes

2021-07-02 17:31 UTC, jennydaman commented on src/components/Plugin/Plugin.jsx
> +    console.log(this.state.pluginData)
Delete

2021-07-02 17:35 UTC, zrthxn commented on src/components/Plugin/components/PluginBody/PluginBody.jsx
> +const removeEmail = (authors) => Array.isArray(authors) ?
Yes iirc there is in some places, like mapping the string to an array to make the list of authors.
But this was also put in as a measure to accommodate arrays, when we eventually fix the authors list being a string of all authors to an array.

2021-07-02 17:36 UTC, zrthxn commented on src/components/Plugin/Plugin.jsx
> +    console.log(this.state.pluginData)
Sorry, will do

2021-07-02 17:55 UTC, closed without merging