Fix bug plugin count in search results
FNNDSC/ChRIS_store_ui pull request #252
Opened 2021-11-02 16:32 UTC by EUGINELETHAL

@zrthxn fixes #246

2021-11-02 17:12 UTC, zrthxn requested changes

2021-11-02 17:12 UTC, zrthxn commented on src/components/Plugins/Plugins.jsx
> +    }
Just for kicks, can you condense this into a single line?

2021-11-02 19:03 UTC, EUGINELETHAL commented
yah let me condense into two
lines


On Tue, Nov 2, 2021 at 8:12 PM Alisamar Husain ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/components/Plugins/Plugins.jsx
> <https://github.com/FNNDSC/ChRIS_store_ui/pull/252#discussion_r741304485>:
>
> > +    let pluginsCount;
> +
> +    if (plugins.totalCount > 0) {
> +      pluginsCount = plugins.totalCount;
> +    } else {
> +      pluginsCount = 0;
> +    }
>
> Just for kicks, can you condense this into a single line?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FNNDSC/ChRIS_store_ui/pull/252#pullrequestreview-795702603>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGE2SA7O4UI52GRF2Q5X633UKALXRANCNFSM5HG4UN3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-03 14:37 UTC, EUGINELETHAL commented on src/components/Plugins/Plugins.jsx
> +    }
@zrthxn i have refactored the code into a single statement,thanks for feedback

2021-11-03 14:45 UTC, zrthxn approved these changes

2021-11-03 15:18 UTC, merged