fixed plugin search issue under pagination section
FNNDSC/ChRIS_store_ui pull request #268
Opened 2022-04-05 07:42 UTC by somya51p

@jennydaman Please review the PR.

![Screenshot from 2022-04-05 13-10-47](https://user-images.githubusercontent.com/64978837/161703808-42f2740d-01fc-4bf8-8aa1-701386249f73.png)

2022-04-05 18:22 UTC, jennydaman commented
Hey @somya51p sorry for not noticing your comment on issue #246.

Could you explain to me why this bug is happening? Your fix seems like a band-aid solution.

2022-04-06 06:10 UTC, somya51p commented
> Hey @somya51p sorry for not noticing your comment on issue #246.
> 
> Could you explain to me why this bug is happening? Your fix seems like a band-aid solution.

@jennydaman For the pagination offset it was **showing 1 to -1**, which is irrelevant, so I have just tried to replace it according to the `plugins.totalCount` as totalCount = -1 is coming from the backend side as discussed in issue #246 earlier.

2022-04-07 07:46 UTC, jennydaman commented
Ah, thanks @somya51p, Please forgive my bad memory.

I do remember this discussion, I'm not sure but I think I might've said somewhere that it'd be better to fix this at the level of the library `@fnndsc/chrisstoreapi`? Or perhaps at a higher level, with an explanation? Ideally we would like to separate application logic from display logic.

I also see this line of code which should probably be used:

https://github.com/FNNDSC/ChRIS_store_ui/pull/268/files#diff-21ceed2791318acc4d4ba806f53e82b4d3c6013e3a5de8373c219aa9c4979e00R371

2022-04-07 12:23 UTC, somya51p commented
@jennydaman I get your point, in case of no result it should obviously show something like - 
![Screenshot from 2022-04-07 17-48-50](https://user-images.githubusercontent.com/64978837/162197115-eef95693-9067-4e21-a59c-e72a9acf9a54.png)

and would this code be satisfactory for the above case? -

![Screenshot from 2022-04-07 17-52-47](https://user-images.githubusercontent.com/64978837/162197666-d2c3781b-3e82-48cd-b379-4a1e792471a8.png)

2022-04-08 17:48 UTC, jennydaman commented
I don't understand the context of your screenshot, would you generate a patch instead? To do so, you can run

```
git diff > changes.patch
```

Then paste the contents of changes.patch here.

2022-04-09 10:10 UTC, somya51p commented
> I don't understand the context of your screenshot, would you generate a patch instead? To do so, you can run
> 
> ```
> git diff > changes.patch
> ```
> 
> Then paste the contents of changes.patch here.

@jennydaman Please have a look!
```
diff --git a/src/components/Plugins/Plugins.jsx b/src/components/Plugins/Plugins.jsx
index 1748db8..51047d2 100644
--- a/src/components/Plugins/Plugins.jsx
+++ b/src/components/Plugins/Plugins.jsx
@@ -416,11 +416,11 @@ export class Plugins extends Component {
                             <p style={{ fontSize: '1.25em', margin: '0', color: 'black', fontWeight: '600' }}>
                                 {pluginsCount} plugins found
                             </p>
-                            Showing {paginationOffset + 1} to {' '}
+                            Showing {Math.min(pluginsCount, paginationOffset + 1)} to {' '}
                             {
                               // eslint-disable-next-line no-nested-ternary
-                              (paginationOffset + paginationLimit > plugins.totalCount) ?
-                                plugins.totalCount
+                              (paginationOffset + paginationLimit > pluginsCount) ?
+                                pluginsCount
                                 :
                                 (paginationOffset > 0) ?
                                   paginationOffset
```
![Screenshot from 2022-04-09 15-37-54](https://user-images.githubusercontent.com/64978837/162567340-464219cb-2013-4b6a-aeb4-edceafe8ae06.png)

2022-04-21 11:59 UTC, somya51p commented
@jennydaman Please review, I have tested for the plugins it is working and added these outside the return statement for code quality improvement.

For lint disabling comment `// eslint-disable-next-line no-nested-ternary`
we can implement that way, but I don't think it's as good a way.

```
// no-nested-ternary rule disallows nested ternary expressions
    const pluginsLast=(paginationOffset + paginationLimit > pluginsCount) ?
    pluginsCount : paginationLimit;
    if (paginationOffset + paginationLimit > pluginsCount)
          pluginsLast = pluginsCount;
    else if (paginationOffset > 0)
          pluginsLast = paginationOffset;
    else
          pluginsLast = paginationLimit;
    
```

2022-04-22 07:38 UTC, jennydaman requested changes

2022-04-22 07:38 UTC, jennydaman commented on src/components/Plugins/Plugins.jsx
> +                            Showing {Math.min(pluginsCount, paginationOffset + 1)} to {pluginsLast}
The only situation where `pluginCount < paginationOffset + 1` would be where `pluginCount == 0`, in which case, it might be better to instead conditionally render something like "No plugins shown" or just omit this text instead. If we can get rid of this `Math.min` call, the what and why of this line of code would be more apparent by a quick glance.

2022-04-22 07:38 UTC, jennydaman commented on src/components/Plugins/Plugins.jsx
> +    const pluginsLast=(paginationOffset + paginationLimit > pluginsCount) ?
Nested ternary is hard to understand and there seems to be logic branch redundancy, I think this would do the same thing as:

```javascript
const pluginsLast = Math.min(paginationOffset + paginationLimit, pluginsCount);
```

- if no plugins, then `pluginsCount = 0`, so `pluginsLast = 0` :heavy_check_mark: 
- if on last page, then `paginationOffset + paginationLimit >= pluginsCount`, so `pluginsLast = pluginsCount` :heavy_check_mark: 
- if not on last page (implying there are multiple pages), then `paginationOffset + paginationLimit < pluginsCount`, so `pluginsLast = paginationOffset + paginationLimit` :heavy_check_mark:

2022-04-22 07:44 UTC, somya51p commented on src/components/Plugins/Plugins.jsx
> +    const pluginsLast=(paginationOffset + paginationLimit > pluginsCount) ?
I got you! I will try to implement what you have suggested asap.

2022-04-30 15:09 UTC, somya51p commented
@jennydaman I have tried to implement the logic which you have suggested. Please have a look into it and suggest changes if any.
![Screenshot from 2022-04-30 20-32-25](https://user-images.githubusercontent.com/64978837/166111109-5ab29279-1b80-4df9-99f8-690cb0fd9a52.png)
![Screenshot from 2022-04-30 20-34-13](https://user-images.githubusercontent.com/64978837/166111114-b3ba316e-354a-4455-a168-d55d8290749a.png)

2022-11-09 15:12 UTC, jennydaman commented
We should fix this in the upstream client library https://github.com/FNNDSC/fnndsc/issues/76

2022-11-09 15:12 UTC, closed without merging